### ISSUE TITLE
KeyError: 'can_checkout'

### ISSUE THREAD

**Issue by tegar737** [amiruldev20/shopeebot#1]
checkout error

[*] Flash Sale telah tiba
[*] Menambah item ke cart...
[*] Checkout item...
Traceback (most recent call last):
  File "C:\start.py", line 103, in <module>
    bot.checkout(PaymentInfo(
  File "C:\bot.py", line 244, in checkout
    data = self.__checkout_get(payment, item)
  File "C:\bot.py", line 223, in __checkout_get
    can_checkout=data["can_checkout"],
KeyError: 'can_checkout'

**Comment by amiruldev20** [comment]
udah ga work baru bbrp hari yg lalu, blm smpet update

**Comment by tegar737** [comment]
oala mangkanya skrng rada ribet bikin yang auto checkout wkwkwk

**Comment by RafalZawidczak** [comment]
Any update?

**Comment by amiruldev20** [comment]
next time
